### ISSUE TITLE
Difficulty setting up looker_deployer in pyenv, virtualenv

### ISSUE THREAD

**Issue by billweils** [looker-open-source/looker_deployer#49]
New Looker customer - working through setting up looker_deployer on Ubuntu 18.04

Is there anyone successfully deploying looker_deployer under pyenv, virtualenv who is willing to review/zoom call to assist?

Having difficulty getting the pyenv, virtual env setup correct to enable looker_deployer to run ----  getting the following errors:

when within virtualenv (python 3.8.3) --- gives back an ImportError: cannot import name 'get_args''
 
ldeploy -h 

Traceback (most recent call last):
  File "/usr/local/bin/ldeploy", line 7, in <module>
    from looker_deployer.cli import main
  File "/home/ubuntu/.local/lib/python3.6/site-packages/looker_deployer/cli.py", line 2, in <module>
    from looker_deployer.commands import deploy_boards, deploy_code, deploy_connections
  File "/home/ubuntu/.local/lib/python3.6/site-packages/looker_deployer/commands/deploy_boards.py", line 2, in <module>
    from looker_sdk import models
  File "/home/ubuntu/.local/lib/python3.6/site-packages/looker_sdk/__init__.py", line 27, in <module>
    from looker_sdk.rtl import serialize
  File "/home/ubuntu/.local/lib/python3.6/site-packages/looker_sdk/rtl/serialize.py", line 45, in <module>
    import cattr
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cattr/__init__.py", line 1, in <module>
    from .converters import Converter, GenConverter, UnstructureStrategy
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cattr/converters.py", line 18, in <module>
    from ._compat import (
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cattr/_compat.py", line 31, in <module>
    from typing import get_args, get_origin  # NOQA
ImportError: cannot import name 'get_args'

**Comment by michaelcramer** [comment]
@billweils is this still an issue? Typically the error you're describing is due to pip modules not being installed.
Basic install use with pyenv would be:
pyenv virtualenv 3.8.3 ldeploy
pyenv activate ldeploy
pip install looker_deployer

**Comment by billweils** [comment]
No. No longer an issue.  I have worked through the various components/packages - and I have ldeploy working on Ubuntu 18.04, RedHat 7 and RedHat 8.
